openapi: 3.0.0
info:
  title: New age
  description: New age app API
  version: 0.1.9

servers:
- url: "http://localhost:4001/api"
  description: local server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth/sign-up:
    post:
      tags: 
      -  auth
      requestBody:
        description: Create User
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                birthday:
                  type: date
                email:
                  type: string
                password:
                  type: string
            example:
              firstName: alex
              lastName: rodriguez
              birthday: 1998/15/02
              email: 123Bh@newage.io   
              password: 123Bh   
      responses:
        '200':
          description: Create User

  /auth/sign-in:
    post:
      tags: 
        -  auth
      requestBody:
        description: JWT bearer authorization
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
            example:
              email: 123Bh@newage.io
              password: 123Bh   
      responses:
        '200':
          description: login successfully

  /auth/me:
    get:
      tags:
        - auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /users/{userId} :
    put:
      tags:
        - auth
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          schema: 
            type: string
            example: d3d4d7c1-4934-43b7-b67f-9e40b999c34f
          required: true 
      requestBody:
        description: Change user
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
            example:
              firstName: Jason
              lastName: Williams   
      responses:
        '200':
          description: User was changed successfully 

    delete:
      tags:
        - auth
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          schema: 
            type: string
            example: fe400d80-1bc9-4097-8437-17fc666d17d4
          required: true 
      responses:
        '200':
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string         
